service: power-digital-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 10
  environment:
    DB_HOST: energy-monitor-db.ci1q4okokkkd.us-east-1.rds.amazonaws.com
    DB_PORT: '5432'
    DB_NAME: energy_monitor
    DB_USERNAME: emadmin
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID, ''}
    MICROSOFT_CLIENT_ID: ${env:MICROSOFT_CLIENT_ID, ''}
    NODE_ENV: production
  vpc:
    securityGroupIds:
      - sg-0adda6a999e8d5d9a
    subnetIds:
      - subnet-00ebf6d39c526567f
      - subnet-07b8c60f262ea05f8
      - subnet-058418d1bc1a8adfa

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          method: '*'
          path: /api/{proxy+}
      - httpApi:
          method: '*'
          path: /api

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
