export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    mfaSetup: '/auth/mfa/setup',
    mfaVerify: '/auth/mfa/verify',
    mfaValidate: '/auth/mfa/validate',
    mfaStatus: '/auth/mfa/status',
    mfaDisable: '/auth/mfa',
  },
  buildings: '/buildings',
  meters: '/meters',
  alerts: '/alerts',
  alertRules: '/alert-rules',
  readings: '/readings',
  hierarchy: '/hierarchy',
  concentrators: '/concentrators',
  faultEvents: '/fault-events',
  tariffs: '/tariffs',
  invoices: '/invoices',
  users: '/users',
  tenantUnits: '/tenant-units',
  auditLogs: '/audit-logs',
  notificationLogs: '/notification-logs',
  alertEngine: '/alert-engine',
  reports: '/reports',
  integrations: '/integrations',
  supportedTypes: '/integrations/supported-types',
  tenants: '/tenants',
  apiKeys: '/api-keys',
  roles: '/roles',
  permissions: '/roles/permissions',
} as const;
