export const APP_ROUTES = {
  login: '/login',
  privacyPolicy: '/privacy-policy',
  dashboard: '/',
  platform: '/dashboard/platform',
  executive: '/dashboard/executive',
  executiveSite: '/dashboard/executive/:siteId',
  compare: '/dashboard/compare',
  buildings: '/buildings',
  buildingDetail: '/buildings/:buildingId',
  meters: '/meters',
  alerts: '/alerts',
  alertRules: '/alerts/rules',
  escalation: '/alerts/escalation',
  notifications: '/alerts/notifications',
  alertsHistory: '/alerts/history',
  monitoring: {
    realtime: '/monitoring/realtime',
    drilldown: '/monitoring/drilldown/:siteId',
    demand: '/monitoring/demand/:siteId',
    quality: '/monitoring/quality/:siteId',
    devices: '/monitoring/devices',
    faultHistory: '/monitoring/fault-history/:meterId',
    metersByType: '/monitoring/meters/type',
    generationIndex: '/monitoring/generation',
    generationSite: '/monitoring/generation/:siteId',
    modbusMapIndex: '/monitoring/modbus-map',
    modbusMapSite: '/monitoring/modbus-map/:siteId',
    concentrator: '/monitoring/concentrator/:concentratorId',
    meterDetail: '/monitoring/meter/:meterId',
    meterReadings: '/monitoring/meter/:meterId/readings/:month',
  },
  billing: {
    invoices: '/billing',
    rates: '/billing/rates',
    history: '/billing/history',
    approve: '/billing/approve',
    myInvoice: '/billing/my-invoice',
  },
  reports: '/reports',
  reportsScheduled: '/reports/scheduled',
  integrations: '/integrations',
  integrationsStatus: '/integrations/status',
  integrationsConfig: '/integrations/config',
  integrationsSyncLog: '/integrations/sync-log',
  analytics: {
    benchmark: '/analytics/benchmark',
    trends: '/analytics/trends',
    patterns: '/analytics/patterns',
  },
  components: '/components',
  profile: '/profile',
  admin: {
    users: '/admin/users',
    tenants: '/admin/tenants',
    hierarchy: '/admin/hierarchy',
    audit: '/admin/audit',
    auditChanges: '/admin/audit/changes',
    auditAccess: '/admin/audit/access',
    settings: '/admin/settings',
    apiKeys: '/admin/api-keys',
    roles: '/admin/roles',
    companies: '/admin/companies',
    deletionRequests: '/admin/deletion-requests',
  },
} as const;
