#!/usr/bin/env node
/**
 * CYB-19: Generate Software Bill of Materials (SBOM).
 *
 * Usage:
 *   node scripts/generate-sbom.mjs [--output-json path] [--output-md path]
 *
 * Reads package.json from backend and frontend, extracts all dependencies,
 * and outputs a CycloneDX-lite JSON + summary Markdown.
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BACKEND_PKG = resolve(__dirname, '..', 'package.json');
const FRONTEND_PKG = resolve(__dirname, '..', '..', 'frontend', 'package.json');
const DEFAULT_JSON = resolve(__dirname, '..', '..', 'docs', 'sbom.json');
const DEFAULT_MD = resolve(__dirname, '..', '..', 'docs', 'sbom-summary.md');

/* ── Parse ── */

function readPackageJson(path, label) {
  const pkg = JSON.parse(readFileSync(path, 'utf-8'));
  const deps = Object.entries(pkg.dependencies ?? {}).map(([name, version]) => ({
    name,
    version: String(version).replace(/^[\^~]/, ''),
    scope: 'runtime',
    component: label,
  }));
  const devDeps = Object.entries(pkg.devDependencies ?? {}).map(([name, version]) => ({
    name,
    version: String(version).replace(/^[\^~]/, ''),
    scope: 'development',
    component: label,
  }));
  return { name: pkg.name, version: pkg.version, deps, devDeps };
}

/* ── CycloneDX-lite JSON ── */

function buildCycloneDx(backendPkg, frontendPkg) {
  const allComponents = [
    ...backendPkg.deps.map(d => toComponent(d)),
    ...backendPkg.devDeps.map(d => toComponent(d)),
    ...frontendPkg.deps.map(d => toComponent(d)),
    ...frontendPkg.devDeps.map(d => toComponent(d)),
  ];

  return {
    bomFormat: 'CycloneDX',
    specVersion: '1.5',
    version: 1,
    metadata: {
      timestamp: new Date().toISOString(),
      tools: [{ vendor: 'energy-monitor', name: 'generate-sbom.mjs', version: '1.0.0' }],
      component: {
        type: 'application',
        name: 'energy-monitor-v2',
        version: backendPkg.version ?? '0.0.1',
      },
    },
    components: allComponents,
  };
}

function toComponent(dep) {
  return {
    type: 'library',
    name: dep.name,
    version: dep.version,
    scope: dep.scope === 'runtime' ? 'required' : 'optional',
    properties: [{ name: 'component', value: dep.component }],
  };
}

/* ── Summary Markdown ── */

function buildMarkdown(backendPkg, frontendPkg) {
  const backendTotal = backendPkg.deps.length + backendPkg.devDeps.length;
  const frontendTotal = frontendPkg.deps.length + frontendPkg.devDeps.length;
  const grandTotal = backendTotal + frontendTotal;

  const lines = [
    '# SBOM Summary — monitoreo-v2',
    '',
    `> Auto-generated by \`scripts/generate-sbom.mjs\`. ${grandTotal} total packages.`,
    '> Re-generate: `npm run sbom`',
    '',
    '> CYB-19: Inventory of all HW/SW components (Anexo 07).',
    '> Full CycloneDX JSON: `docs/sbom.json`',
    '',
    '## Overview',
    '',
    '| Component | Runtime | Dev | Total |',
    '|-----------|--------:|----:|------:|',
    `| Backend | ${backendPkg.deps.length} | ${backendPkg.devDeps.length} | ${backendTotal} |`,
    `| Frontend | ${frontendPkg.deps.length} | ${frontendPkg.devDeps.length} | ${frontendTotal} |`,
    `| **Total** | **${backendPkg.deps.length + frontendPkg.deps.length}** | **${backendPkg.devDeps.length + frontendPkg.devDeps.length}** | **${grandTotal}** |`,
    '',
    '---',
    '',
    '## Backend Runtime Dependencies',
    '',
    '| Package | Version |',
    '|---------|---------|',
  ];

  for (const d of backendPkg.deps.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`| ${d.name} | ${d.version} |`);
  }

  lines.push('');
  lines.push('## Frontend Runtime Dependencies');
  lines.push('');
  lines.push('| Package | Version |');
  lines.push('|---------|---------|');

  for (const d of frontendPkg.deps.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`| ${d.name} | ${d.version} |`);
  }

  lines.push('');
  return lines.join('\n');
}

/* ── Main ── */

export function generate() {
  const backendPkg = readPackageJson(BACKEND_PKG, 'backend');
  const frontendPkg = readPackageJson(FRONTEND_PKG, 'frontend');
  const cycloneDx = buildCycloneDx(backendPkg, frontendPkg);
  const markdown = buildMarkdown(backendPkg, frontendPkg);

  return {
    cycloneDx,
    json: JSON.stringify(cycloneDx, null, 2),
    markdown,
    backendRuntime: backendPkg.deps.length,
    backendDev: backendPkg.devDeps.length,
    frontendRuntime: frontendPkg.deps.length,
    frontendDev: frontendPkg.devDeps.length,
    total: backendPkg.deps.length + backendPkg.devDeps.length + frontendPkg.deps.length + frontendPkg.devDeps.length,
  };
}

const isMain = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isMain) {
  const jsonIdx = process.argv.indexOf('--output-json');
  const mdIdx = process.argv.indexOf('--output-md');
  const jsonPath = jsonIdx >= 0 ? resolve(process.argv[jsonIdx + 1]) : DEFAULT_JSON;
  const mdPath = mdIdx >= 0 ? resolve(process.argv[mdIdx + 1]) : DEFAULT_MD;

  const result = generate();
  writeFileSync(jsonPath, result.json, 'utf-8');
  writeFileSync(mdPath, result.markdown, 'utf-8');
  console.log(`SBOM: ${result.total} packages (${result.backendRuntime}+${result.backendDev} backend, ${result.frontendRuntime}+${result.frontendDev} frontend) → ${jsonPath}`);
}
